### ISSUE TITLE
Несколько меток

### ISSUE THREAD

**Issue by sailorsamoor** [yhunter-ru/yamaps#1]
Привет. Возможно-ли установить несколько меток на карту?

**Comment by yhunter-ru** [comment]
Да, можно. Только в визуальном редакторе не реализованно пока. Можно внутрь шорткода карты вставить несколько шорткодов меток:

`[yamap center="58.0102,56.2497" zoom="16" type="yandex#map" controls="typeSelector;zoomControl;searchControl;routeEditor;rulerControl;trafficControl;fullscreenControl;geolocationControl"]
[yaplacemark coord="58.0096,56.2455" color="#ff0505" name="Метка 1"]
[yaplacemark coord="58.0106,56.2536" color="#2bab22" name="Метка 2"]
[/yamap]`

Для относительного удобства можно делать несколько карт с одной меткой визуально, потом скопировать шорткоды всех меток в одну карту.

**Comment by sailorsamoor** [comment]
Удачная идея. Можно в кнопку и не вставлять - кнопка удобна для быстрой вставки карты в запись прямо в процессе редактирования.
