### ISSUE TITLE
2 ошибки валидации

### ISSUE THREAD

**Issue by aidardev** [yhunter-ru/yamaps#11]
Привет! 
До вставки карты на сайт не было ошибок валидации. После вставки появились 2 ошибки: не нужный элемент <style></style> и нету alt у img. Плиз хочу сделать валидную верстку, твой плагин единственный нормальный, но 2 ошибки напрягают))

**Comment by aidardev** [comment]
А так плагин отличный!

**Comment by yhunter-ru** [comment]
Спасибо, исправлю в следующем обновлении.

**Comment by aidardev** [comment]
> Спасибо, исправлю в следующем обновлении.

Спасибо!)
