### ISSUE TITLE
не экранируются кавычки

### ISSUE THREAD

**Issue by ildarkhasanshin** [yhunter-ru/yamaps#3]
в поле *Название метки*
т.е. получаем в редакторе name=""тест""
в коде hintContent: ""
и при повторном открытии на редактирование это поле пустое

wp 4.9.8
yamaps 0.5.1

**Comment by yhunter-ru** [comment]
Спасибо, исправлю.

**Comment by yhunter-ru** [comment]
В 0.5.2 исправлено
