### ISSUE TITLE
Объект ym, который создает плагин

### ISSUE THREAD

**Issue by rainjeck** [yhunter-ru/yamaps#5]
Плагин создает объект ym. ym использует Яндекс.Метрика. Измените название.
Из-за этого не работает метрика.

**Comment by yhunter-ru** [comment]
Я пока встречал только один сайт, где происходило подобное. И там имя объекта ym присваивалось в коде счетчика искусственно. Оно могло быть любым. И после смены имени, метрика заработала. При этом я не видел, чтобы сам Яндекс сейчас выдавал код счетчика с таким именем объекта. 

Если подтвердится, что такой объект использует непосредственно метрикой, я подумаю над сменой имени. Что довольно проблематично, так как выпущено уже несколько коммерческих расширений, использующих нынешнее наименование.

**Comment by rainjeck** [comment]
Насколько я поняла, это теперь новая версия метрики. Так как до этого имя у них было другое.
https://yandex.ru/support/metrika/code/install-several-counters.html

У кого стоит старый объект - все ок. А если ставить новые, то сталкиваешься с неработающим скриптом метрики.

Нужно просто сменить имя объекта, который создает плагин:

> var ym = {};

**Comment by yhunter-ru** [comment]
Спасибо, ясно теперь откуда ноги растут. Собственно, имя объекта тоже только в примере документации указано, а не в самом api метрики. Можете переименовать упоминания ym на ym2, например, в этом коде — и все заработает. 

`(window, document, "script", "https://mc.yandex.ru/metrika/tag.js", "ym2");

ym2(XXXXXX, "init", {});
ym2(YYYYYY, "init", { webvisor: true });`

В плагине менять, вероятно, пока не буду. Но еще подумаю. Слишком много людей это затронет и придется вручную обновлять им дополнения к плагину.

**Comment by rainjeck** [comment]
Счетчик выдается с теперь с ym. 
Думаю, стоит упомянуть данный момент в описании к плагину, например. 
Мы-то, программеры, найдем откуда ноги растут, а рядовой пользователь - для него это будет большой проблемой. Рядовой пользователь просто copy-paste :)

**Comment by yhunter-ru** [comment]
Хорошо, буду исправлять. Ждите следующую версию плагина.

**Comment by yhunter-ru** [comment]
Название объекта изменено в 0.6.3
