### ISSUE TITLE
Яндекс карта в Elementor

### ISSUE THREAD

**Issue by Olegggggggg** [yhunter-ru/yamaps#7]
Здравствуйте. Было бы неплохо если бы Вы добавили возможность использования Вашего плагина в Elementor.

**Comment by yhunter-ru** [comment]
Можете вставлять блок редактора и использовать. Специального блока точно не будет. По крайней мере, если если никто не заплатит за его разработку или не напишет его сам.

**Comment by Olegggggggg** [comment]
Сколько будет стоить разработка такого блока у Вас?

**Comment by yhunter-ru** [comment]
Порядка ~30000 ₽

**Comment by Olegggggggg** [comment]
Понял, спасибо.
