### ISSUE TITLE
Не сохраняются ссылки

### ISSUE THREAD

**Issue by zeleniy87** [yhunter-ru/yamaps#8]
При нанесении на карту меток со разными ссылками на каждой метке если рисуем карту за один сеанс (редакцию, сессию) все ссылки и отметки сохраняются нормально. Если необходимо позже добавить на карту отметку, то старые ссылки в отметках будут неправильными, а новые сохраняются нормально. Используем ссылки вида /podkljuchit/?npunkt=Симферополь&street=Октябрьская&house=36. Это ссылка на форму, при клике на отметку на карте происходит перенаправление на страницу с формой, в которой заполняются поля. Если нанести на карту такую отметку и сохранить, то все нормально. Стоит закрыть редактор, открыть заново карту и нанести отметку, старые ссылки обрезаются до вида /podkljuchit/?npunkt на всех старых отметках.

**Comment by yhunter-ru** [comment]
Здравствуйте. Закоммитил сюда исправление 0.6.13. Можете потестировать. Если все в порядке, скоро опубликую в репозитории плагинов WP.

**Comment by zeleniy87** [comment]
Добрый день, сегодня установлю, потестим, оптику Вам. Спасибо.
--
Отправлено из Mail.ru для Android понедельник, 16 марта 2020г., 09:42 +03:00 от yhunter-ru  notifications@github.com :

**Comment by zeleniy87** [comment]
Установил версию 0.6.13. Ссылки сохраняются на отметках, но при сохранении, а затем при повторном реадктировании в старых ссылках вместо & прописывается &amp;. Из-за этого заполнение формы не происходит.
--
Отправлено из Mail.ru для Android понедельник, 16 марта 2020г., 09:42 +03:00 от yhunter-ru  notifications@github.com :

**Comment by yhunter-ru** [comment]
OK, удалось воссоздать проблему только в Гутенберге - это он меняет амперсанды. Закоммитил правку. Версия плагина не изменилась, можете поменять только файл shortcode_parser.js из папки js. Обновите страницу и/или сбросьте кэш в браузере с редактором после замены файла, чтобы точно подгружалась обновленная версия.

**Comment by zeleniy87** [comment]
Теперь работает, спасибо!
--
Отправлено из Mail.ru для Android понедельник, 16 марта 2020г., 15:11 +03:00 от yhunter-ru  notifications@github.com :
